Wed Sep 29 17:22:10 CEST 2021 Thread[main,5,main] Cleanup action starting
ERROR XBM0J: El directorio C:\Users\juamb\Documents\Estudios\Data Access\005. Derby ya existe.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:295)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$10.run(StorageFactoryService.java:822)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:798)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1754)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1022)
	at org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(FileMonitor.java:48)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:650)
	at org.apache.derby.impl.jdbc.EmbedConnection$5.run(EmbedConnection.java:4067)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.impl.jdbc.EmbedConnection.createPersistentService(EmbedConnection.java:4061)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2654)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:435)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.iapi.jdbc.AutoloadedDriver.connect(AutoloadedDriver.java:136)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at org.apache.derby.impl.tools.ij.ij.dynamicConnection(ij.java:1495)
	at org.apache.derby.impl.tools.ij.ij.ConnectStatement(ij.java:1325)
	at org.apache.derby.impl.tools.ij.ij.ijStatement(ij.java:1106)
	at org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(utilMain.java:353)
	at org.apache.derby.impl.tools.ij.utilMain.go(utilMain.java:251)
	at org.apache.derby.impl.tools.ij.Main.go(Main.java:229)
	at org.apache.derby.impl.tools.ij.Main.mainCore(Main.java:184)
	at org.apache.derby.impl.tools.ij.Main.main(Main.java:75)
	at org.apache.derby.tools.ij.main(ij.java:59)
Cleanup action completed
Wed Sep 29 17:22:10 CEST 2021 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: No se ha podido crear la base de datos 'C:\Users\juamb\Documents\Estudios\Data Access\005. Derby', consulte la excepción siguiente para obtener más información.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:115)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:141)
	at org.apache.derby.impl.jdbc.Util.seeNextException(Util.java:252)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2661)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:435)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.iapi.jdbc.AutoloadedDriver.connect(AutoloadedDriver.java:136)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at org.apache.derby.impl.tools.ij.ij.dynamicConnection(ij.java:1495)
	at org.apache.derby.impl.tools.ij.ij.ConnectStatement(ij.java:1325)
	at org.apache.derby.impl.tools.ij.ij.ijStatement(ij.java:1106)
	at org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(utilMain.java:353)
	at org.apache.derby.impl.tools.ij.utilMain.go(utilMain.java:251)
	at org.apache.derby.impl.tools.ij.Main.go(Main.java:229)
	at org.apache.derby.impl.tools.ij.Main.mainCore(Main.java:184)
	at org.apache.derby.impl.tools.ij.Main.main(Main.java:75)
	at org.apache.derby.tools.ij.main(ij.java:59)
Caused by: ERROR XJ041: No se ha podido crear la base de datos 'C:\Users\juamb\Documents\Estudios\Data Access\005. Derby', consulte la excepción siguiente para obtener más información.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory.java:170)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:75)
	... 22 more
Caused by: ERROR XBM0J: El directorio C:\Users\juamb\Documents\Estudios\Data Access\005. Derby ya existe.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:295)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$10.run(StorageFactoryService.java:822)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:798)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1754)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1022)
	at org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(FileMonitor.java:48)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:650)
	at org.apache.derby.impl.jdbc.EmbedConnection$5.run(EmbedConnection.java:4067)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.impl.jdbc.EmbedConnection.createPersistentService(EmbedConnection.java:4061)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2654)
	... 19 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: El directorio C:\Users\juamb\Documents\Estudios\Data Access\005. Derby ya existe.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:115)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:230)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:431)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:360)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2405)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2662)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:435)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.iapi.jdbc.AutoloadedDriver.connect(AutoloadedDriver.java:136)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at org.apache.derby.impl.tools.ij.ij.dynamicConnection(ij.java:1495)
	at org.apache.derby.impl.tools.ij.ij.ConnectStatement(ij.java:1325)
	at org.apache.derby.impl.tools.ij.ij.ijStatement(ij.java:1106)
	at org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(utilMain.java:353)
	at org.apache.derby.impl.tools.ij.utilMain.go(utilMain.java:251)
	at org.apache.derby.impl.tools.ij.Main.go(Main.java:229)
	at org.apache.derby.impl.tools.ij.Main.mainCore(Main.java:184)
	at org.apache.derby.impl.tools.ij.Main.main(Main.java:75)
	at org.apache.derby.tools.ij.main(ij.java:59)
Caused by: ERROR XBM0J: El directorio C:\Users\juamb\Documents\Estudios\Data Access\005. Derby ya existe.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:295)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$10.run(StorageFactoryService.java:822)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:798)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1754)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1022)
	at org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(FileMonitor.java:48)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:650)
	at org.apache.derby.impl.jdbc.EmbedConnection$5.run(EmbedConnection.java:4067)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.impl.jdbc.EmbedConnection.createPersistentService(EmbedConnection.java:4061)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2654)
	... 19 more
============= end nested exception, level (1) ===========
============= begin nested exception, level (2) ===========
ERROR XBM0J: El directorio C:\Users\juamb\Documents\Estudios\Data Access\005. Derby ya existe.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:295)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$10.run(StorageFactoryService.java:822)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(StorageFactoryService.java:798)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(BaseMonitor.java:1754)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(BaseMonitor.java:1022)
	at org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(FileMonitor.java:48)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Monitor.java:650)
	at org.apache.derby.impl.jdbc.EmbedConnection$5.run(EmbedConnection.java:4067)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.impl.jdbc.EmbedConnection.createPersistentService(EmbedConnection.java:4061)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(EmbedConnection.java:2654)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:435)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.iapi.jdbc.AutoloadedDriver.connect(AutoloadedDriver.java:136)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at org.apache.derby.impl.tools.ij.ij.dynamicConnection(ij.java:1495)
	at org.apache.derby.impl.tools.ij.ij.ConnectStatement(ij.java:1325)
	at org.apache.derby.impl.tools.ij.ij.ijStatement(ij.java:1106)
	at org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(utilMain.java:353)
	at org.apache.derby.impl.tools.ij.utilMain.go(utilMain.java:251)
	at org.apache.derby.impl.tools.ij.Main.go(Main.java:229)
	at org.apache.derby.impl.tools.ij.Main.mainCore(Main.java:184)
	at org.apache.derby.impl.tools.ij.Main.main(Main.java:75)
	at org.apache.derby.tools.ij.main(ij.java:59)
============= end nested exception, level (2) ===========
Cleanup action completed
----------------------------------------------------------------
Wed Sep 29 17:22:37 CEST 2021:
 Iniciando instancia a816c00e-017c-3226-1a4f-00000ea0e608 de Derby, versión The Apache Software Foundation - Apache Derby - 10.15.2.0 - (1873585): 
en el directorio de base de datos C:\Users\juamb\Documents\Estudios\Data Access\005. Derby\db con el cargador de clases jdk.internal.loader.ClassLoaders$AppClassLoader@659e0bfd
Cargado desde file:/C:/Users/juamb/Documents/Estudios/Data%20Access/Engines/derby/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=16.0.2+7-67
user.dir=C:\Users\juamb\Documents\Estudios\Data Access\Engines\derby\bin
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=null
Cargador de clases de base de datos iniciado - derby.database.classpath=''
